version: '3.5'

services:
  nginx:
    image: nginx
    container_name: ${SERVICE_NAME}_${CONTAINER_NAME_WEB}
    restart: always
    ports:
      - ${NGINX_IP:-0.0.0.0}:80:80
      - ${NGINX_IP:-0.0.0.0}:443:443
    volumes:
      - ${SERVICE_DATA}/${SERVICE_NAME}/conf.d:/etc/nginx/conf.d:Z
      - ${SERVICE_CONFIG}/vhost.d:/etc/nginx/vhost.d:Z
      - ${SERVICE_DATA}/${SERVICE_NAME}/html:/usr/share/nginx/html:Z
      - ${SERVICE_DATA}/${SERVICE_NAME}/certs:/etc/nginx/certs:ro
      - ${SERVICE_DATA}/${SERVICE_NAME}/htpasswd:/etc/nginx/htpasswd:ro
    networks:
      - service

  gen:
    image: jwilder/docker-gen
    container_name: ${SERVICE_NAME}_${CONTAINER_NAME_GEN}
    depends_on:
    - nginx
    - letsencrypt
    command: -notify-sighup ${SERVICE_NAME}_${CONTAINER_NAME_WEB} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    volumes:
      - ${SERVICE_DATA}/${SERVICE_NAME}/conf.d:/etc/nginx/conf.d:Z
      - ${SERVICE_CONFIG}/vhost.d:/etc/nginx/vhost.d:Z
      - ${SERVICE_DATA}/${SERVICE_NAME}/html:/usr/share/nginx/html:Z
      - ${SERVICE_DATA}/${SERVICE_NAME}/certs:/etc/nginx/certs:ro
      - ${SERVICE_DATA}/${SERVICE_NAME}/htpasswd:/etc/nginx/htpasswd:ro
      - ${SERVICE_CONFIG}/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - service

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${SERVICE_NAME}_${CONTAINER_NAME_LETSENCRYPT}
    restart: always
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${SERVICE_NAME}_${CONTAINER_NAME_GEN}
      NGINX_PROXY_CONTAINER: ${SERVICE_NAME}_${CONTAINER_NAME_WEB}
    volumes:
      - ${SERVICE_DATA}/${SERVICE_NAME}/conf.d:/etc/nginx/conf.d:Z
      - ${SERVICE_CONFIG}/vhost.d:/etc/nginx/vhost.d:Z
      - ${SERVICE_DATA}/${SERVICE_NAME}/html:/usr/share/nginx/html:Z
      - ${SERVICE_DATA}/${SERVICE_NAME}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - service

networks:
  service:
    name: ${SERVICE_NETWORK}
